version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: new090_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/new090
      - public-data:/new090/public
      - tmp-data:/new090/tmp
      - log-data:/new090/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/new090/public
      - tmp-data:/new090/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
